build:
	        gcc -o kp main.c filesLoader.c knapsack_O.c consoleInterface.c -pthread
advenced:
		gcc -o kp main.c filesLoader.c knapsack_A.c consoleInterface.c -pthread
base:
		gcc -o kp main.c filesLoader.c knapsack_B.c consoleInterface.c -pthread
debug:
	        gcc -g -o kp main.c filesLoader.c knapsack.c consoleInterface.c -pthread
clean:
	        rm kp
run:
	        ./kp ${var1} ${var2} ${var3} ${var4} ${var5}

rundebug:
	        gdb kp


